- hosts: 'webservers'
  become: true
  tasks:
    - name: 'Download Zabbix repo'
      uri:
        url: 'https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+xenial_all.deb'
        dest: '/tmp/zabbix_repo.deb'
        force: false

    - name: 'Install Zabbix repo from deb file'
      apt:
        deb: '/tmp/zabbix_repo.deb'
        state: 'present'

    - name: 'Install Zabbix server'
      apt:
        name: 'zabbix-server-mysql'
        state: 'present'

    - name: 'Start Zabbix server service'
      service:
        name: 'zabbix-server'
        enabled: false
        state: started

    - name: 'Install Zabbix agent'
      apt:
        name: 'zabbix-agent'
        state: 'present'

    - name: 'Start Zabbix agent service'
      service:
        name: 'zabbix-agent'
        enabled: false
        state: started
