- hosts: 'zabbix_server'
  become: true
  tasks:
    - name: 'Download Zabbix v{{ zabbix_version }} repository'
      uri:
        url: 'https://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+{{ ansible_distribution_release }}_all.deb'
        dest: '/tmp/zabbix_repo_v{{ zabbix_version }}.deb'
        force: false

    - name: 'Install Zabbix repo from deb file'
      apt:
        deb: '/tmp/zabbix_repo_v{{ zabbix_version }}.deb'
        state: 'present'

    - name: 'Install Zabbix server with {{ DB_engine }} DB'
      apt:
        name: 'zabbix-server-{{ DB_engine }}'
        state: 'present'
      notify: 'start server'

  handlers:
    - name: 'zabbix-server service start'
      listen: 'start server'
      service:
        name: 'zabbix-server'
        enabled: false
        state: started
      become: true
